# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  scheduler:
    build:
      context: .
    environment:
      - BROKER_URI=amqp://admin:secret@rabbitmq:5672/
      - SECRET_KEY=secret
      - POSTGRES_DB=scheduler_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST=scheduler_db
      - POSTGRES_PORT=5432
    ports:
      - 8001:8000
    depends_on:
      - scheduler_db
      - rabbitmq
    networks:
      - aihub-network

  scheduler_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: scheduler_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - aihub-network

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - 5673:5672
    networks:
      - aihub-network

volumes:
  db-data:
    driver: local

networks:
  aihub-network:
    external: true