apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scheduler
  template:
    metadata:
      labels:
        io.kompose.service: scheduler
    spec:
      containers:
        - name: scheduler
          image: asia-southeast1-docker.pkg.dev/aihub-hosting/aihub/scheduler:v2
          ports:
            - containerPort: 8001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: scheduler-config
            - secretRef:
                name: scheduler-secrets
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: scheduler

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: scheduler-db
  name: scheduler-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scheduler-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: scheduler-db
    spec:
      containers:
        - name: scheduler-db
          image: postgres:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: scheduler-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scheduler-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/scheduler
              name: scheduler-data
      restartPolicy: Always
      volumes:
        - name: scheduler-data
          persistentVolumeClaim:
            claimName: scheduler-data

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: scheduler-db
  name: scheduler-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: scheduler-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: scheduler-data
  name: scheduler-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:latest
          ports:
            - containerPort: 5672
              protocol: TCP
          envFrom:
            - configMapRef:
                name: scheduler-config
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: scheduler-secrets
                  key: RABBITMQ_DEFAULT_PASS
      restartPolicy: Always
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "amqp"
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: rabbitmq

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: rabbitmq-data
  name: rabbitmq-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: airena-worker
  name: airena-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: airena-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: airena-worker
    spec:
      containers:
        - name: airena-worker
          image: asia-southeast1-docker.pkg.dev/aihub-478008/aihub/airena-worker:v1
          ports:
            - containerPort: 15921
              protocol: TCP
          envFrom:
            - configMapRef:
                name: scheduler-config
            - secretRef:
                name: scheduler-secrets
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: airena-worker
  name: airena-worker
spec:
  ports:
    - name: "15921"
      port: 15921
      targetPort: 15921
  selector:
    io.kompose.service: airena-worker
