apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secret
          image: asia-southeast1-docker.pkg.dev/aihub-hosting/aihub/user-service:v2.0.2
          name: user-service
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: users-db
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: users-db
    spec:
      containers:
        - name: users-db
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/users
              name: users-data
      restartPolicy: Always
      volumes:
        - name: users-data
          persistentVolumeClaim:
            claimName: users-data

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: users-db
  name: users-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: users-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: users-data
  name: users-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
