# Generated by Django 5.1.6 on 2025-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Lecturer", "Lecturer"),
                    ("Student", "Student"),
                    ("TeachingAssistant", "Teaching Assistant"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users_service.role"
            ),
        ),
    ]
